### ISSUE TITLE
ProxyPort Options in PodDisruptor.InjectHTTPFaults not working

### ISSUE THREAD

**Issue by MrsDaehin** [grafana/xk6-disruptor#255]
hi,

I have been trying to change the proxyPort in which i should add the fault to. With the following instruction I get an error that the port is still the default one ( port 80 ).

```js
podDisruptor.injectHTTPFaults(fault, "1m", {"ProxyPort": 8080})
```

```sh
osboxes@osboxes:~$ kubectl get service -n mock
NAME                       TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
metrics-api-test-service   ClusterIP   10.0.62.189   <none>        8080/TCP   64s
```

But the Error shown in the k6 terminal: 

```
ERRO[0024] GoError: error injecting fault: validate fault port: pod metrics-api-test-metrics-server-d475d9dcb-8k5fd doesn't listen to the port 80
running at reflect.methodValueCall (native)
setup   at disrupt (file:///home/osboxes/Documents/keda-performance/test-delays.js:110:32(32))  executor=shared-iterations scenario=disrupt source=stacktrace
```

**Comment by pablochacin** [comment]
Hi @MrsDaehin, the purpose of the `ProxyPort` is to change the default port that the xk6-disruptor agent uses for its internal work. In most cases, there's no need for changing this option.

According to the output of the  `kubectl` command, the service is exposing the port `8080`. What you need to do is to change the `port` option in the [fault](https://k6.io/docs/javascript-api/xk6-disruptor/api/faults/http/).

**Comment by MrsDaehin** [comment]
i am an idiot! thanks! :)
