### ISSUE TITLE
The new dashboard does not work with xk6-disruptor

### ISSUE THREAD

**Issue by fslevoaca-ionos** [grafana/xk6-disruptor#387]
Hi, 
The new dashboard k6 feature released in version [v0.49.0](https://github.com/grafana/k6/releases/tag/v0.49.0) does not work with xk6-disruptor.

Is it possible to make it available also here ?

**Comment by pablochacin** [comment]
@fslevoaca-ionos Thanks for reporting this issue. It should be fixed with the [release v0.3.11](https://github.com/grafana/xk6-disruptor/releases/tag/v0.3.11)

**Comment by fslevoaca-ionos** [comment]
Thank you and best regards !

**Comment by fslevoaca-ionos** [comment]
Is there any .deb binary available ?

**Comment by pablochacin** [comment]
@fslevoaca-ionos we have identified an issue with the release process that is preventing the publication of the artifacts https://github.com/grafana/xk6-disruptor/issues/390

**Comment by pablochacin** [comment]
@fslevoaca-ionos this issue is now solved and .deb package is available.
