### ISSUE TITLE
Envoy Support and Configuration for ServiceDisruptor with Istio

### ISSUE THREAD

**Issue by denisqsound** [grafana/xk6-disruptor#397]
Hello xk6-disruptor team,

I am exploring the use of ServiceDisruptor in a Kubernetes cluster and have a question regarding its compatibility and configuration with Envoy (istio). Specifically, I would like to know if there is support for scenarios where the network configuration is managed through Istio (istio-iptables), and the pods behind the service do not have a defined `ports` section in their configuration.

Here's what I'm trying to achieve:
I want to set up ServiceDisruptor for a service that is backed by pods. These pods have their network traffic managed via Istio, and as such, they don't include the typical `ports` configuration like this:

```
  ports:
    - name: http
      containerPort: 3333
      protocol: TCP
```

Could you please provide guidance or documentation on how to configure ServiceDisruptor in such a setup? Any examples or best practices would be greatly appreciated.

While attempting to configure this, I am facing the following error:

```
GoError: error injecting fault: unable to get command for pod "frontend-bb577bb46-4qkjv": pod "frontend-bb577bb46-4qkjv" does not export port "3333"
```

Thank you for your assistance.

**Comment by pablochacin** [comment]
@denisqsound Unfortunately we don't currently support this configuration.

**Comment by denisqsound** [comment]
Okay, thanks 😞
