### ISSUE TITLE
Failed to Inject HTTP fault: Command terminated with exit code 1

### ISSUE THREAD

**Issue by dgzlopes** [grafana/xk6-disruptor#46]
I'm not able to inject HTTP faults using the PodDisruptor. I get the following error:
```
INFO[0006] target: ["querier-54f7cf5487-tpm5x"]          source=console
ERRO[0007] GoError: command terminated with exit code 1
        at reflect.methodValueCall (native)
        at file:///Users/dgzlopes/go/src/github.com/grafana/xk6-disruptor/examples/pod_disruptor.js:26:34(32)
        at native  executor=per-vu-iterations scenario=default source=stacktrace
```

This is the script that I'm using:
```javascript
import { PodDisruptor } from 'k6/x/disruptor';

const selector = {
        namespace: 'demo',
        select: {
                labels: {
                        name: 'querier',
                },
        },
}

const fault = {
        averageDelay: 100,
        errorRate: 0.1,
        errorCode: 500
}

export default function () {
        const disruptor = new PodDisruptor(selector)
        const targets = disruptor.targets()
        if (targets.length != 1) {
        	throw new Error("expected list to have one target")
        }

       console.log("target: " + JSON.stringify(targets))
       disruptor.injectHTTPFaults(fault, 30)
}
```

The pod I'm targeting is running properly. Also, the ephemeral container is there:
```
Ephemeral Containers:
  xk6-agent:
    Container ID:   docker://aca764daeee2fd701d756ad33f9ab96e71498cdf9ddc7d8e1dc9cbb210b573b2
    Image:          ghcr.io/grafana/xk6-disruptor-agent
    Image ID:       docker-pullable://ghcr.io/grafana/xk6-disruptor-agent@sha256:1b3d8a8f7d4e9d28fcaf55b831a5d43cdfb145a6bd8fc8970499a3acedabd438
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 15 Nov 2022 12:27:09 +0100
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
```

I logged what we are passing to the exec helper and got this:
```
querier-54f7cf5487-tpm5x [xk6-disruptor-agent http -d 30s -a 100 -v 0 -e 500 -r 0.1 -b ]
```

There are no logs on the ephemeral container (or at least, I couldn't see them).

**My local setup:** 
- Kubernetes v1.25.2 (Docker Desktop - Mac M1) 
- Built from the latest code in main.

**Comment by pablochacin** [comment]
Thanks for reporting this @dgzlopes. The problem seems to be the `-b` option at the end of the command. This is a bug introduced in [this commit](https://github.com/grafana/xk6-disruptor/commit/7c504ce18e6808360ac346ae2690c75b31fa14dc#diff-3662e45ee6c60cc0ee0837acee2b32ecc4ed9e80685af36b1ba83cd292af00d9R283).

The `-b` argument should be added conditionally to the agent command because it is not mandatory in the fault definition. 
I will submit a fix soon, as the change is trivial.

**Comment by dgzlopes** [comment]
Amazing. Thanks @pablochacin ❤️

**Comment by dgzlopes** [comment]
Btw, I tried this locally, with the -b option removed, and looks like it still fails 👀 

```
EXEC COMMAND querier-54f7cf5487-jmj6d [xk6-disruptor-agent http -d 30s -a 100 -v 0 -e 500 -r 0.1]
EXEC COMMAND DONE
EXEC ERROR querier-54f7cf5487-jmj6d command terminated with exit code 1
ERRO[0001] GoError: command terminated with exit code 1
        at reflect.methodValueCall (native)
        at file:///Users/dgzlopes/go/src/github.com/grafana/xk6-disruptor/examples/pod_disruptor.js:26:34(32)
        at native  executor=per-vu-iterations scenario=default source=stacktrace
 ```

**Comment by dgzlopes** [comment]
Also, should we propagate errors better from the agent to k6? The current method doesn't provide that much info.

**Comment by pablochacin** [comment]
> Also, should we propagate errors better from the agent to k6? The current method doesn't provide that much info.
As it is executed as a process, the only thing we could do is to show the stdot/stderr in the execution of the command from the extensio
